name: syncfusion_localizations
description: Syncfusion Localizations package contains localized text for 77 cultures for all the applicable Syncfusion Flutter Widgets. 
version: 20.4.42
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_localizations

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.15.0 <0.20.0"
  syncfusion_flutter_core: ^20.4.42

flutter:
